USE [master]
GO

/****** Object:  Database [busStationBase]    Script Date: 06.05.2021 10:27:10 ******/
CREATE DATABASE [busStationBase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'busStationBase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\busStationBase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'busStationBase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\busStationBase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [busStationBase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [busStationBase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [busStationBase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [busStationBase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [busStationBase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [busStationBase] SET ARITHABORT OFF 
GO

ALTER DATABASE [busStationBase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [busStationBase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [busStationBase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [busStationBase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [busStationBase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [busStationBase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [busStationBase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [busStationBase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [busStationBase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [busStationBase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [busStationBase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [busStationBase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [busStationBase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [busStationBase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [busStationBase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [busStationBase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [busStationBase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [busStationBase] SET RECOVERY FULL 
GO

ALTER DATABASE [busStationBase] SET  MULTI_USER 
GO

ALTER DATABASE [busStationBase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [busStationBase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [busStationBase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [busStationBase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [busStationBase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [busStationBase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [busStationBase] SET QUERY_STORE = OFF
GO

ALTER DATABASE [busStationBase] SET  READ_WRITE 
GO

